version: '3'
services:
  nginx:
    container_name: lab1_nginx
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ../code:/code
      - ./nginx-configs/:/etc/nginx/conf.d/
    links:
      - php
  php:
    container_name: lab1_php
    image: php:8-fpm
    volumes:
      - ../code:/code
