version: '3.7'
services:
  nginx:
    container_name: lab6_nginx
    image: nginx:stable-alpine
    ports:
      - '8082:80'
    volumes:
      - ../app:/var/www/symfony_docker
      - ./nginx-config/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
      - database
  database:
    container_name: lab6_mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: symfony_DB
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '4306:3306'
    volumes:
      - ../mysql:/var/lib/mysql
  php:
    container_name: lab6_php
    build:
      context: ../php
    ports:
      - '9000:9000'
    volumes:
      - ../app:/var/www/symfony_docker
    links:
      - database
      
